"""Unit tests for zencontrol-dump helpers."""

from pathlib import Path

from zencontrol_simulator.dump import (
    format_api_timing_report,
    sanitize_controller_label,
    write_yaml,
)


def test_sanitize_controller_label_basic():
    assert sanitize_controller_label("Living Room") == "living-room"


def test_sanitize_controller_label_punctuation_and_case():
    assert sanitize_controller_label("  ZenControl #1 — Main!! ") == "zencontrol-1-main"


def test_sanitize_controller_label_collapses_spaces():
    assert sanitize_controller_label("A   B___C") == "a-b-c"


def test_sanitize_controller_label_empty_fallback():
    assert sanitize_controller_label("!!!") == "controller"
    assert sanitize_controller_label("") == "controller"


def test_format_api_timing_report_empty():
    assert format_api_timing_report({}) == "# API response times (msec): (no samples)\n"


def test_format_api_timing_report_ascii_table():
    report = format_api_timing_report({
        "QUERY_DALI_EAN": {"min": 1.0, "avg": 2.5, "max": 4.0, "n": 2, "total": 1500.0},
        "DALI_QUERY_LEVEL": {"min": 3.0, "avg": 3.0, "max": 3.0, "n": 1, "total": 100.0},
    })
    lines = report.strip().splitlines()
    assert lines[0] == "# API response times (msec):"
    assert lines[1].startswith("# +")
    assert "| API" in lines[2]
    assert "total s" in lines[2]
    assert "DALI_QUERY_LEVEL" in lines[4]
    assert lines[4].rstrip().endswith("|     0.1 |")  # 100ms → ceil to 0.1s
    assert "QUERY_DALI_EAN" in lines[5]
    assert lines[5].rstrip().endswith("|     1.5 |")  # 1500ms → 1.5s
    assert lines[-1].startswith("# +")


def test_write_yaml_appends_timing_report(tmp_path: Path):
    out = tmp_path / "world.yaml"
    write_yaml(
        out,
        {
            "controller": {
                "bind_host": "0.0.0.0",
                "bind_port": 5108,
                "mac": "00:00:00:00:00:00",
                "label": "Test",
                "version": [2, 2, 0],
                "startup_complete": True,
                "dali_ready": True,
                "event_mode": 1,
                "heartbeat_interval": 0,
            },
            "lights": [],
            "groups": [],
            "devices": [],
            "profiles": {"current": 0, "last_scheduled": 0, "items": []},
            "system_variables": [],
        },
        timing_stats={
            "QUERY_CONTROLLER_LABEL": {
                "min": 1.2, "avg": 1.2, "max": 1.2, "n": 1, "total": 1200.0,
            },
        },
    )
    text = out.read_text(encoding="utf-8")
    assert text.startswith("# Auto-generated by zencontrol-dump")
    assert "# API response times (msec):" in text
    assert "QUERY_CONTROLLER_LABEL" in text
    assert "total s" in text
    assert "| 1.2 |" in text
    assert text.strip().endswith("+")
